// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Administrativo.Entities.ClienteAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("TipoDocumento");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "43372251034",
                            Email = "joao.silva@email.com",
                            Nome = "João Silva",
                            TipoDocumento = "Cpf"
                        },
                        new
                        {
                            Id = 2,
                            Documento = "74694481024",
                            Email = "maria.oliveira@email.com",
                            Nome = "Maria Oliveira",
                            TipoDocumento = "Cpf"
                        },
                        new
                        {
                            Id = 3,
                            Documento = "31868352011",
                            Email = "carlos.santos@email.com",
                            Nome = "Carlos Santos",
                            TipoDocumento = "Cpf"
                        },
                        new
                        {
                            Id = 4,
                            Documento = "17293524021",
                            Email = "ana.costa@email.com",
                            Nome = "Ana Costa",
                            TipoDocumento = "Cpf"
                        },
                        new
                        {
                            Id = 5,
                            Documento = "84617462057",
                            Email = "lucas.ferreira@email.com",
                            Nome = "Lucas Ferreira",
                            TipoDocumento = "Cpf"
                        },
                        new
                        {
                            Id = 6,
                            Documento = "53820257000159",
                            Email = "contato@autopecascentral.com.br",
                            Nome = "Auto Peças Central Ltda",
                            TipoDocumento = "Cnpj"
                        },
                        new
                        {
                            Id = 7,
                            Documento = "19183615000195",
                            Email = "oficinatoninho@email.com",
                            Nome = "Oficina do Toninho ME",
                            TipoDocumento = "Cnpj"
                        },
                        new
                        {
                            Id = 8,
                            Documento = "75294528000185",
                            Email = "logistica@rapidosul.com.br",
                            Nome = "Transportadora Rápido Sul",
                            TipoDocumento = "Cnpj"
                        },
                        new
                        {
                            Id = 9,
                            Documento = "42168936000152",
                            Email = "frota@xyzlocadora.com.br",
                            Nome = "Locadora de Veículos XYZ",
                            TipoDocumento = "Cnpj"
                        },
                        new
                        {
                            Id = 10,
                            Documento = "85303964000182",
                            Email = "vendas@bateriaspotencia.com.br",
                            Nome = "Comercial de Baterias Potência",
                            TipoDocumento = "Cnpj"
                        });
                });

            modelBuilder.Entity("Domain.Administrativo.Entities.ServicoAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoPadrao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "MTR-001",
                            Nome = "Troca de Óleo do Motor",
                            PrecoPadrao = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "FLT-002",
                            Nome = "Troca de Filtro de Ar",
                            PrecoPadrao = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "FRE-003",
                            Nome = "Troca de Pastilhas de Freio",
                            PrecoPadrao = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "SUS-004",
                            Nome = "Alinhamento e Balanceamento",
                            PrecoPadrao = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Codigo = "MTR-005",
                            Nome = "Limpeza de Bicos Injetores",
                            PrecoPadrao = 180.00m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Codigo = "ELT-006",
                            Nome = "Troca de Bateria",
                            PrecoPadrao = 80.00m
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Codigo = "ARC-007",
                            Nome = "Higienização de Ar Condicionado",
                            PrecoPadrao = 130.00m
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Codigo = "SUS-008",
                            Nome = "Troca de Amortecedores Dianteiros",
                            PrecoPadrao = 300.00m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Codigo = "EMB-009",
                            Nome = "Substituição do Kit de Embreagem",
                            PrecoPadrao = 600.00m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Codigo = "GRL-010",
                            Nome = "Revisão Preventiva Geral",
                            PrecoPadrao = 250.00m
                        });
                });

            modelBuilder.Entity("Domain.Administrativo.Entities.UsuarioAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            TipoUsuario = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Administrativo.Entities.VeiculoAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDono")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDono");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdDono = 1,
                            Marca = "Chevrolet",
                            Modelo = "Onix",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 2,
                            IdDono = 1,
                            Marca = "Volkswagen",
                            Modelo = "Gol",
                            Placa = "XYZ1A23"
                        },
                        new
                        {
                            Id = 3,
                            IdDono = 1,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "DEF5678"
                        },
                        new
                        {
                            Id = 4,
                            IdDono = 2,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "GHI9B12"
                        },
                        new
                        {
                            Id = 5,
                            IdDono = 2,
                            Marca = "Fiat",
                            Modelo = "Argo",
                            Placa = "JKL3456"
                        },
                        new
                        {
                            Id = 6,
                            IdDono = 3,
                            Marca = "Hyundai",
                            Modelo = "HB20",
                            Placa = "MNO4C56"
                        },
                        new
                        {
                            Id = 7,
                            IdDono = 3,
                            Marca = "Ford",
                            Modelo = "Ka",
                            Placa = "PQR7890"
                        },
                        new
                        {
                            Id = 8,
                            IdDono = 3,
                            Marca = "Renault",
                            Modelo = "Kwid",
                            Placa = "STU5D78"
                        },
                        new
                        {
                            Id = 9,
                            IdDono = 4,
                            Marca = "Jeep",
                            Modelo = "Compass",
                            Placa = "VWX1234"
                        },
                        new
                        {
                            Id = 10,
                            IdDono = 5,
                            Marca = "Nissan",
                            Modelo = "Kicks",
                            Placa = "YZA6E90"
                        },
                        new
                        {
                            Id = 11,
                            IdDono = 5,
                            Marca = "Chevrolet",
                            Modelo = "Tracker",
                            Placa = "BCD5678"
                        },
                        new
                        {
                            Id = 12,
                            IdDono = 6,
                            Marca = "Volkswagen",
                            Modelo = "Saveiro",
                            Placa = "EFG7F12"
                        },
                        new
                        {
                            Id = 13,
                            IdDono = 6,
                            Marca = "Fiat",
                            Modelo = "Fiorino",
                            Placa = "HIJ9012"
                        },
                        new
                        {
                            Id = 14,
                            IdDono = 6,
                            Marca = "Peugeot",
                            Modelo = "Partner",
                            Placa = "KLM8G34"
                        },
                        new
                        {
                            Id = 15,
                            IdDono = 7,
                            Marca = "Chevrolet",
                            Modelo = "Montana",
                            Placa = "NOP3456"
                        },
                        new
                        {
                            Id = 16,
                            IdDono = 8,
                            Marca = "Mercedes-Benz",
                            Modelo = "Sprinter",
                            Placa = "QRS9H56"
                        },
                        new
                        {
                            Id = 17,
                            IdDono = 8,
                            Marca = "Iveco",
                            Modelo = "Daily",
                            Placa = "TUV7890"
                        },
                        new
                        {
                            Id = 18,
                            IdDono = 8,
                            Marca = "Ford",
                            Modelo = "Transit",
                            Placa = "WXY0I78"
                        },
                        new
                        {
                            Id = 19,
                            IdDono = 9,
                            Marca = "Fiat",
                            Modelo = "Mobi",
                            Placa = "ZAB1234"
                        },
                        new
                        {
                            Id = 20,
                            IdDono = 10,
                            Marca = "Volkswagen",
                            Modelo = "Kombi",
                            Placa = "CDE1J90"
                        });
                });

            modelBuilder.Entity("Domain.Estoque.Entities.ItemEstoqueAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("SaldoReservado")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ItensEstoque");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "INS-001",
                            Nome = "Óleo Motor Sintético 5W30",
                            PrecoVenda = 45.90m,
                            Saldo = 50.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "INS-002",
                            Nome = "Óleo Motor Semissintético 15W40",
                            PrecoVenda = 38.50m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PEC-001",
                            Nome = "Filtro de Óleo",
                            PrecoVenda = 35.00m,
                            Saldo = 15.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PEC-002",
                            Nome = "Filtro de Ar do Motor",
                            PrecoVenda = 42.00m,
                            Saldo = 20.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PEC-003",
                            Nome = "Filtro de Cabine (Ar Condicionado)",
                            PrecoVenda = 30.00m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "PEC-004",
                            Nome = "Pastilha de Freio Dianteira",
                            PrecoVenda = 120.00m,
                            Saldo = 8.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "PEC-005",
                            Nome = "Pastilha de Freio Traseira",
                            PrecoVenda = 95.00m,
                            Saldo = 3.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "INS-003",
                            Nome = "Fluido de Freio DOT 4",
                            PrecoVenda = 25.00m,
                            Saldo = 30.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Frasco"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "INS-004",
                            Nome = "Chumbo para Balanceamento",
                            PrecoVenda = 18.00m,
                            Saldo = 5.500m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Kg"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "INS-005",
                            Nome = "Descarbonizante Spray",
                            PrecoVenda = 22.00m,
                            Saldo = 10.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Frasco"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "PEC-006",
                            Nome = "Kit O-ring Bico Injetor",
                            PrecoVenda = 15.00m,
                            Saldo = 25.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "PEC-016",
                            Nome = "Correia Dentada",
                            PrecoVenda = 85.00m,
                            Saldo = 6.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "PEC-017",
                            Nome = "Tensor da Correia Dentada",
                            PrecoVenda = 110.00m,
                            Saldo = 4.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "PEC-018",
                            Nome = "Vela de Ignição",
                            PrecoVenda = 140.00m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "PEC-007",
                            Nome = "Bateria 60Ah",
                            PrecoVenda = 350.00m,
                            Saldo = 4.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "PEC-008",
                            Nome = "Bateria 45Ah",
                            PrecoVenda = 280.00m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "PEC-009",
                            Nome = "Terminal de Bateria",
                            PrecoVenda = 12.00m,
                            Saldo = 40.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Par"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "PEC-014",
                            Nome = "Lâmpada H4",
                            PrecoVenda = 25.00m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Unidade"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "PEC-015",
                            Nome = "Lâmpada Pingo T10",
                            PrecoVenda = 10.00m,
                            Saldo = 50.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Par"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "INS-006",
                            Nome = "Higienizador Granada",
                            PrecoVenda = 28.00m,
                            Saldo = 18.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Frasco"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "INS-007",
                            Nome = "Gás Refrigerante R134a",
                            PrecoVenda = 85.00m,
                            Saldo = 3.200m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Kg"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "PEC-010",
                            Nome = "Amortecedor Dianteiro",
                            PrecoVenda = 450.00m,
                            Saldo = 2.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Par"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "PEC-011",
                            Nome = "Kit Batente Amortecedor Dianteiro",
                            PrecoVenda = 80.00m,
                            Saldo = 5.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "PEC-012",
                            Nome = "Kit Embreagem Completo",
                            PrecoVenda = 650.00m,
                            Saldo = 0.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Jogo"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "INS-008",
                            Nome = "Fluido de Transmissão Manual",
                            PrecoVenda = 55.00m,
                            Saldo = 12.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "PEC-013",
                            Nome = "Palheta Limpador Parabrisa",
                            PrecoVenda = 45.00m,
                            Saldo = 10.000m,
                            SaldoReservado = 0m,
                            Tipo = "Peca",
                            UnidadeMedida = "Par"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "INS-009",
                            Nome = "Aditivo Radiador Concentrado",
                            PrecoVenda = 32.00m,
                            Saldo = 24.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "INS-010",
                            Nome = "Água Desmineralizada",
                            PrecoVenda = 8.00m,
                            Saldo = 60.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "INS-011",
                            Nome = "Estopa Polimento",
                            PrecoVenda = 15.00m,
                            Saldo = 2.500m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Kg"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "INS-012",
                            Nome = "Desengraxante Concentrado",
                            PrecoVenda = 20.00m,
                            Saldo = 15.000m,
                            SaldoReservado = 0m,
                            Tipo = "Insumo",
                            UnidadeMedida = "Litro"
                        });
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.ItemNecessario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdItemOrdemServico")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("ItemEstoque", "Domain.OrdemServico.Entities.ItemNecessario.ItemEstoque#ItemEstoqueOrdemServico", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UnidadeMedida")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdItemOrdemServico");

                    b.HasIndex("IdOrdemServico");

                    b.HasIndex("Status");

                    b.ToTable("ItemNecessario");
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.OrdemServicoAggregateRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AprovadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DescartadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EntregueEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecebidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("Cliente", "Domain.OrdemServico.Entities.OrdemServicoAggregateRoot.Cliente#ClienteOrdemServico", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Veiculo", "Domain.OrdemServico.Entities.OrdemServicoAggregateRoot.Veiculo#VeiculoOrdemServico", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Marca")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Modelo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Placa")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TokenAprovacao")
                        .IsUnique();

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExecucaoFinalizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExecucaoIniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejeitadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorCobrado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.ComplexProperty<Dictionary<string, object>>("ServicoCatalogo", "Domain.OrdemServico.Entities.Servico.ServicoCatalogo#ServicoCatalogo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico");

                    b.HasIndex("Status");

                    b.ToTable("ItensServicos");
                });

            modelBuilder.Entity("Domain.Administrativo.Entities.VeiculoAggregateRoot", b =>
                {
                    b.HasOne("Domain.Administrativo.Entities.ClienteAggregateRoot", null)
                        .WithMany()
                        .HasForeignKey("IdDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.ItemNecessario", b =>
                {
                    b.HasOne("Domain.OrdemServico.Entities.Servico", null)
                        .WithMany("ItensNecessarios")
                        .HasForeignKey("IdItemOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.OrdemServico.Entities.OrdemServicoAggregateRoot", null)
                        .WithMany()
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.Servico", b =>
                {
                    b.HasOne("Domain.OrdemServico.Entities.OrdemServicoAggregateRoot", null)
                        .WithMany("Servicos")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.OrdemServicoAggregateRoot", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Domain.OrdemServico.Entities.Servico", b =>
                {
                    b.Navigation("ItensNecessarios");
                });
#pragma warning restore 612, 618
        }
    }
}
